### ISSUE TITLE
请求开放同步状态数据的跨域访问

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [openana/mirrors.xjtu.edu.cn#1]
同步状态数据的 url 是 https://mirrors.xjtu.edu.cn/api/status.json ，该数据也可用于其他项目（例如 [mirrorz](https://mirrorz.org)），故请求开放其跨域访问，或者几个特定站的跨域访问。

具体方法为添加 `Access-Control-Allow-Origin: *` 的头或者（在`referer: https://mirrorz.org/`时）添加 `Access-Control-Allow-Origin: https://mirrorz.org`

目前存在通过本地获取贵站状态生成的供 mirrorz 使用的站点信息，但随着时间推移已经较为过时，参考 https://mirrorz.org/site/XJTU 与 https://github.com/tuna/mirrorz/blob/master/static/tmp/xjtu.json

参考 https://github.com/PKUOSC/issues/issues/2

**Comment by AirWSW** [comment]
已添加

**Comment by ZenithalHourlyRate** [comment]
感谢。另请参考 https://github.com/tuna/mirrorz/issues/10
