### ISSUE TITLE
mirror request: bioarchlinux

### ISSUE THREAD

**Issue by starsareintherose** [openana/mirrors.xjtu.edu.cn#5]
# Introduction

Name: BioArchLinux
Introduction: Arch Community for Biologists & Arch Repository for Biological Software
Official web: https://bioarchlinux.org/
Github Repo: https://github.com/BioArchLinux/Packages

# Mirror method
```
rsync -rtlivH bioarchlinux.org::sync/ destdir 
```

# Size

30G

**Comment by AirWSW** [comment]
Thanks for your request. Now, you can access its mirror via the following links:
- (HTTPS) https://mirrors.xjtu.edu.cn/bioarchlinux/
- (HTTP) http://mirrors.xjtu.edu.cn/bioarchlinux/
